project:
  type: website

execute:
  freeze: auto  # Re-render only when source changes

website:
  title: "template-quarto-website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



